-- Generated by scripts/export_state.py - do not edit by hand.
--
-- The web app's own tables: deck requests and deck proposals. Committed so
-- that `make rebuild` can put them back, and replayed after data/seed.sql.
--
-- Each row resolves its deck through the slug, so it survives a rebuild that
-- renumbers decks, and is skipped entirely if that deck or card is gone.

PRAGMA foreign_keys = ON;

DELETE FROM deck_proposals;
DELETE FROM deck_requests;

