#!/usr/bin/env python3
"""Write the app-authored tables out to data/app-state.sql.

`make rebuild` reconstructs the database from committed files. Everything else
has a file behind it - ManaBox exports, decklists, seed.sql - but proposals and
deck requests are created by the web app and lived only inside collection.db,
so a rebuild silently threw away every decision recorded in the app.

This is the missing file. `make dump` regenerates it, `make rebuild` replays it.

Rows are keyed to decks by SLUG, not by the autoincrement id, because deck ids
shift whenever a ManaBox binder is added or renamed. Their own ids ARE kept, so
deck_proposals.pairs_with keeps pointing at the right partner.
"""

from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "app-state.sql"

HEADER = """\
-- Generated by scripts/export_state.py - do not edit by hand.
--
-- The web app's own tables: deck requests and deck proposals. Committed so
-- that `make rebuild` can put them back, and replayed after data/seed.sql.
--
-- Each row resolves its deck through the slug, so it survives a rebuild that
-- renumbers decks, and is skipped entirely if that deck or card is gone.

PRAGMA foreign_keys = ON;

DELETE FROM deck_proposals;
DELETE FROM deck_requests;
"""


def lit(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def export(conn: sqlite3.Connection) -> str:
    conn.row_factory = sqlite3.Row
    out = [HEADER]

    req_cols = ["id", "format", "colors", "commander_hint", "strategy", "allow_borrowing",
                "allow_buying", "notes", "status", "response", "created_at"]
    rows = conn.execute(
        "SELECT r.*, d.slug AS deck_slug FROM deck_requests r "
        "LEFT JOIN decks d ON d.id = r.deck_id ORDER BY r.id").fetchall()
    if rows:
        out.append("\n-- Deck requests ------------------------------------------------------------")
    for r in rows:
        vals = ", ".join(lit(r[c]) for c in req_cols)
        deck = ("(SELECT id FROM decks WHERE slug = %s)" % lit(r["deck_slug"])
                if r["deck_slug"] else "NULL")
        out.append(
            f"INSERT INTO deck_requests ({', '.join(req_cols)}, deck_id)\n"
            f"VALUES ({vals}, {deck});")

    prop_cols = ["id", "action", "status", "rationale", "source", "pairs_with",
                 "created_at", "updated_at"]
    rows = conn.execute(
        "SELECT p.*, d.slug AS deck_slug, c.name AS card_name FROM deck_proposals p "
        "JOIN decks d ON d.id = p.deck_id JOIN cards c ON c.oracle_id = p.oracle_id "
        "ORDER BY p.id").fetchall()
    if rows:
        out.append("\n-- Deck proposals -----------------------------------------------------------")
    for r in rows:
        vals = ", ".join(lit(r[c]) for c in prop_cols)
        # INSERT..SELECT with a guard: a proposal for a deck or card that no
        # longer exists is dropped rather than failing the whole rebuild.
        out.append(
            f"INSERT INTO deck_proposals ({', '.join(prop_cols)}, deck_id, oracle_id)\n"
            f"SELECT {vals}, d.id, c.oracle_id\n"
            f"  FROM decks d, cards c\n"
            f" WHERE d.slug = {lit(r['deck_slug'])} AND c.name = {lit(r['card_name'])};")

    out.append("")
    return "\n".join(out)


def main() -> int:
    db = ROOT / "data" / "collection.db"
    if not db.exists():
        print(f"no {db}", file=sys.stderr)
        return 1
    conn = sqlite3.connect(db)
    try:
        OUT.write_text(export(conn), encoding="utf-8")
    finally:
        conn.close()
    reqs = sqlite3.connect(db).execute("SELECT count(*) FROM deck_requests").fetchone()[0]
    props = sqlite3.connect(db).execute("SELECT count(*) FROM deck_proposals").fetchone()[0]
    print(f"Wrote {OUT.relative_to(ROOT)}: {reqs} request(s), {props} proposal(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
